import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function generateAgreementPdf(params: {
  title: string;
  employeeName: string;
  employeeEmail: string;
  date: string;
}): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4

  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontSize = 12;

  page.drawText(params.title, {
    x: 50,
    y: 780,
    size: 18,
    font,
    color: rgb(0, 0, 0),
  });

  const body = `
Employee Name: ${params.employeeName}
Email: ${params.employeeEmail}

Date: ${params.date}

This document confirms the offer of employment.
This agreement is generated by the HR system.
`;

  page.drawText(body, {
    x: 50,
    y: 720,
    size: fontSize,
    font,
    lineHeight: 16,
  });

  return await pdf.save();
}
